import { Shoe } from "./TS";

export const data: Shoe[] = [
  {
    id: 1,
    manufacturer: "Nike",
    shoeType: "Dunk",
    shoeName: "Syracuse",
    shoeSize: 10,
    shoeColor: "Orange",
    shoeQuantity: 1,
    shoePrice: 236,
  },
  {
    id: 2,
    manufacturer: "Nike",
    shoeType: "Dunk",
    shoeName: "Kentucky",
    shoeSize: 10,
    shoeColor: "Blue",
    shoeQuantity: 1,
    shoePrice: 412,
  },
  {
    id: 3,
    manufacturer: "Nike",
    shoeType: "Dunk",
    shoeName: "Michigan",
    shoeSize: 10,
    shoeColor: "Yellow",
    shoeQuantity: 1,
    shoePrice: 156,
  },
  {
    id: 4,
    manufacturer: "Nike",
    shoeType: "Jordan 1",
    shoeName: "Bred",
    shoeSize: 10,
    shoeColor: "Red",
    shoeQuantity: 1,
    shoePrice: 143,
  },
  {
    id: 5,
    manufacturer: "Jordan",
    shoeType: "Retro 1",
    shoeName: "Chicago",
    shoeSize: 10,
    shoeColor: "Red",
    shoeQuantity: 1,
    shoePrice: 123,
  },
  {
    id: 6,
    manufacturer: "Yeazy",
    shoeType: "Boost",
    shoeName: "350",
    shoeSize: 10,
    shoeColor: "Black",
    shoeQuantity: 1,
    shoePrice: 240,
  },
  {
    id: 7,
    manufacturer: "Dunk",
    shoeType: "Nike",
    shoeName: "Jarritos",
    shoeSize: 10,
    shoeColor: "Green",
    shoeQuantity: 1,
    shoePrice: 400,
  },
];
