import { Shoe } from "./TS";

export const data: Shoe[] = [
  {
    Id: 1,
    Manufacturer: "Nike",
    ShoeType: "Dunk",
    ShoeName: "Syracuse",
    ShoeSize: 10,
    ShoeColor: "Orange",
    ShoeQuantity: 1,
    ShoePrice: 236,
  },
  {
    Id: 2,
    Manufacturer: "Nike",
    ShoeType: "Dunk",
    ShoeName: "Kentucky",
    ShoeSize: 10,
    ShoeColor: "Blue",
    ShoeQuantity: 1,
    ShoePrice: 412,
  },
  {
    Id: 3,
    Manufacturer: "Nike",
    ShoeType: "Dunk",
    ShoeName: "Michigan",
    ShoeSize: 10,
    ShoeColor: "Yellow",
    ShoeQuantity: 1,
    ShoePrice: 156,
  },
  {
    Id: 4,
    Manufacturer: "Nike",
    ShoeType: "Jordan 1",
    ShoeName: "Bred",
    ShoeSize: 10,
    ShoeColor: "Red",
    ShoeQuantity: 1,
    ShoePrice: 143,
  },
  {
    Id: 5,
    Manufacturer: "Jordan",
    ShoeType: "Retro 1",
    ShoeName: "Chicago",
    ShoeSize: 10,
    ShoeColor: "Red",
    ShoeQuantity: 1,
    ShoePrice: 123,
  },
  {
    Id: 6,
    Manufacturer: "Yeazy",
    ShoeType: "Boost",
    ShoeName: "350",
    ShoeSize: 10,
    ShoeColor: "Black",
    ShoeQuantity: 1,
    ShoePrice: 240,
  },
  {
    Id: 7,
    Manufacturer: "Dunk",
    ShoeType: "Nike",
    ShoeName: "Jarritos",
    ShoeSize: 10,
    ShoeColor: "Green",
    ShoeQuantity: 1,
    ShoePrice: 400,
  },
];
